name: flutter_navigator
description: A flutter navigator service that allows communication to the Navigator API without build context.
version: 0.1.4
repository: https://github.com/LukeMoody01/flutter_navigator/tree/main/packages/flutter_navigator
issue_tracker: https://github.com/LukeMoody01/flutter_navigator/issues
homepage: https://github.com/LukeMoody01/flutter_navigator

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
